import os
import json
import numpy as np
import pandas as pd
import xgboost as xgb
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

class VectorizedBacktester:
    # Simulates the Execution Node pipeline over historical data in RAM.
    
    def __init__(self, models_dir: str = "the_models", data_dir: str = "the_execution_node/data"):
        self.models_dir = models_dir
        self.data_dir = data_dir
        self.baskets = {}
        self.flat_list = []
        self.meta_labeler = None
        
        # 1. Load the Decoupled Architecture Models
        self._load_payloads()
        
    def _load_payloads(self):
        # Ingests the M1's curated universe and the XGBoost Meta-Labeler.
        universe_path = os.path.join(self.models_dir, "curated_universe.json")
        try:
            with open(universe_path, "r") as f:
                data = json.load(f)
                self.baskets = data.get("baskets", {})
                self.flat_list = data.get("flat_list", [])
            print(f"[SUCCESS] Loaded {len(self.baskets)} baskets from curated_universe.json.")
        except FileNotFoundError:
            print("[CRITICAL] curated_universe.json not found.")
            exit(1)
            
        xgb_path = os.path.join(self.models_dir, "meta_labeler_v2.json")
        try:
            self.meta_labeler = xgb.Booster()
            self.meta_labeler.load_model(xgb_path)
            print("[SUCCESS] Loaded XGBoost Meta-Labeler (meta_labeler_v2.json).")
        except Exception as e:
            print(f"[WARNING] Could not load XGBoost model. Defaulting to pure Stat-Arb. Error: {e}")
            self.meta_labeler = None

    def _fetch_historical_data(self):
        # Loads the massive 3-year 5-minute dataset generated by the M1 Vault.
        # Bypasses yfinance API limits entirely.
        data_path = os.path.join(self.data_dir, "backtest_5m_3yr.parquet")
        
        print(f"[SYSTEM] Loading historical Parquet matrix from {data_path}...")
        try:
            # Pandas reads Parquet exponentially faster than CSV
            df = pd.read_parquet(data_path)
            
            # Ensure index is datetime and sorted
            if not isinstance(df.index, pd.DatetimeIndex):
                df.index = pd.to_datetime(df.index)
            df = df.sort_index()
            
            print(f"[SUCCESS] Historical Matrix Loaded in RAM: {df.shape[0]} rows x {df.shape[1]} columns")
            
            # Forward fill any missing microstructure ticks, then drop remaining NAs
            return df.ffill().dropna()
            
        except FileNotFoundError:
            print(f"[CRITICAL] Historical data vault not found at {data_path}.")
            print("[ACTION] Generate this file on the M1 Research Node and transfer it.")
            exit(1)

    def _apply_cusum_regime_shield(self, target_index: pd.DatetimeIndex, threshold: float = 0.02):
        # THE SHIELD: Reads daily SPY data from the CSV, calculates the CUSUM regime,
        # and aligns the daily state to the 5-minute Parquet index.
        csv_path = os.path.join(self.data_dir, "raw_macro_data.csv")
        
        try:
            macro_df = pd.read_csv(csv_path, index_col='Date', parse_dates=True)
            # Clean, linter-friendly timezone conversion to match the Parquet index
            macro_df.index = pd.to_datetime(macro_df.index, utc=True)
        except Exception as e:
            print(f"[WARNING] Could not load {csv_path}. Defaulting Shield to SAFE. Error: {e}")
            return pd.Series(True, index=target_index)

        spy_daily = macro_df['SPY']
        returns = spy_daily.pct_change().dropna()
        
        # Calculate CUSUM on daily data
        pos_cusum = np.zeros_like(returns)
        neg_cusum = np.zeros_like(returns)
        regime_safe = np.ones_like(returns, dtype=bool) 
        
        for i in range(1, len(returns)):
            pos_cusum[i] = max(0, pos_cusum[i-1] + returns.iloc[i])
            neg_cusum[i] = min(0, neg_cusum[i-1] + returns.iloc[i])
            
            if pos_cusum[i] > threshold or neg_cusum[i] < -threshold:
                regime_safe[i] = False
                pos_cusum[i] = 0 
                neg_cusum[i] = 0
                
        daily_mask = pd.Series(np.insert(regime_safe, 0, True), index=spy_daily.index)
        
        # Project the daily regime state onto the 5-minute tick matrix
        # (e.g., If yesterday triggered the shield, today's intraday ticks are blocked)
        aligned_mask = daily_mask.reindex(target_index, method='ffill').fillna(True)
        return aligned_mask

    def run_simulation(self):
        # 1. Ingest Data
        df = self._fetch_historical_data()
        if df.empty:
            print("[CRITICAL] Parquet dataframe is empty.")
            return

        # 2. Run the Shield
        print("[SYSTEM] Calculating CUSUM Market Regime Shield from Daily Macro CSV...")
        
        # Pass df.index so the Shield can align the daily CSV data to our 5-min ticks
        regime_safe_mask = self._apply_cusum_regime_shield(df.index)
        
        portfolio_returns = pd.Series(0.0, index=df.index)
        
        print(f"[SYSTEM] Simulating {len(self.baskets)} HRP-Allocated Strategies...")
        
        # 3. Iterate through each basket and apply the Engine -> Brain -> Allocator logic
        for spread_name, params in self.baskets.items():
            weights = params.get('weights', {})
            half_life = params.get('half_life', 1.0)
            allocation = params.get('capital_allocation', 0.0)
            
            if allocation <= 0:
                continue
                
            # A. Calculate Synthetic Spread
            spread_val = pd.Series(0.0, index=df.index)
            for ticker, w in weights.items():
                if ticker in df.columns:
                    spread_val += df[ticker] * w
                    
            if spread_val.eq(0).all():
                continue
                    
            # B. THE ENGINE: Calculate Z-Scores
            window = max(int(half_life * 78), 30) # 78 5-min bars per day
            rolling_mean = spread_val.rolling(window=window).mean()
            rolling_std = spread_val.rolling(window=window).std()
            
            # Avoid division by zero
            rolling_std = rolling_std.replace(0, np.nan)
            z_score = (spread_val - rolling_mean) / rolling_std
            
            # Base Signals: Long if Z < -2, Short if Z > 2
            base_signals = pd.Series(0, index=df.index)
            base_signals[z_score < -2.0] = 1
            base_signals[z_score > 2.0] = -1
            
           # C. THE BRAIN: XGBoost Meta-Labeling
            if self.meta_labeler is not None:
                price_change = spread_val.diff()
                tick_dir = np.sign(price_change).replace(0, np.nan).ffill().fillna(1)
                signed_vol = 100 * tick_dir
                
                covar = price_change.rolling(30).cov(price_change.shift(1))
                roll_measure = 2 * np.sqrt(np.abs(covar))
                
                features = pd.DataFrame({
                    'frac_diff': price_change, 
                    'volatility': rolling_std,
                    'signal_strength': z_score,
                    'order_flow_imbalance': signed_vol.rolling(50).sum(),
                    'effective_spread': roll_measure
                }).dropna()
                
                expected_cols = ['frac_diff', 'volatility', 'signal_strength', 'order_flow_imbalance', 'effective_spread']
                features = features[expected_cols]
                
                valid_idx = features.index
                dmatrix = xgb.DMatrix(features)
                win_probs = self.meta_labeler.predict(dmatrix)
                
                # 3. Filter base signals SAFELY without shrinking the array length
                meta_mask = pd.Series(win_probs > 0.5, index=valid_idx)
                
                # Create a blank full-length series, then map the approved signals into it
                filtered_signals = pd.Series(0, index=df.index)
                filtered_signals.loc[valid_idx] = base_signals.loc[valid_idx].where(meta_mask, 0)
                
                base_signals = filtered_signals

            # D. Apply The Shield (Regime Filter)
            final_signals = base_signals.where(regime_safe_mask, 0)
            
            # E. Event-Driven Execution (Triple Barrier Method)
            print(f"  -> Simulating path-dependent trades for {spread_name}...")
            
            # Recreate the volatility scaling used in your training environment
            # EWM span=100 on 5-min bars, scaled to approximate the daily volatility targets
            vol = spread_val.pct_change().ewm(span=100).std().fillna(0) * np.sqrt(78) 
            
            in_position = 0        # 1 for Long, -1 for Short
            entry_price = 0.0
            entry_idx = 0
            current_vol = 0.0
            
            # We must iterate row-by-row to respect the exact path of the trade
            for i in range(1, len(df)):
                current_price = spread_val.iloc[i]
                prev_price = spread_val.iloc[i-1]
                signal = final_signals.iloc[i]
                
                # 1. Look for Entry (if flat)
                if in_position == 0:
                    if signal != 0:
                        in_position = signal
                        entry_price = current_price
                        entry_idx = i
                        # Lock in the volatility at the moment of entry to set the barrier widths
                        current_vol = vol.iloc[i] if vol.iloc[i] > 0 else 0.005 
                
                # 2. Manage Open Position (if active)
                elif in_position != 0:
                    bars_held = i - entry_idx
                    
                    # Calculate Mark-to-Market tick P&L for the equity curve
                    if prev_price != 0:
                        tick_ret = (current_price - prev_price) * in_position * allocation
                    else:
                        tick_ret = 0
                        
                    portfolio_returns.iloc[i] += tick_ret
                    
                    # 3. Check Triple Barriers
                    if entry_price != 0:
                        trade_return = (current_price / entry_price - 1) * in_position
                    else:
                        trade_return = 0
                        
                    # pt_sl=[1, 2] -> Profit Take = 1x Volatility, Stop Loss = 2x Volatility
                    profit_take_threshold = current_vol * 1.0
                    stop_loss_threshold = -(current_vol * 2.0)
                    
                    hit_pt = trade_return >= profit_take_threshold
                    hit_sl = trade_return <= stop_loss_threshold
                    hit_time = bars_held >= 120  # t1=120 (10 hours of 5-min bars)
                    
                    # Exit the trade if any barrier is touched
                    if hit_pt or hit_sl or hit_time:
                        in_position = 0 
                        entry_price = 0.0
                        entry_idx = 0

        # 4. Fetch SPY from the CSV for the baseline comparison
        csv_path = os.path.join(self.data_dir, "raw_macro_data.csv")
        try:
            macro_df = pd.read_csv(csv_path, index_col='Date', parse_dates=True)
            macro_df.index = pd.to_datetime(macro_df.index, utc=True)
            spy_data = macro_df['SPY']
        except Exception as e:
            print(f"[WARNING] Could not load SPY baseline for plotting: {e}")
            spy_data = pd.Series(0.0, index=df.index) # Flatline fallback if CSV is missing

        # 5. Generate Performance Graphics
        self._plot_results(portfolio_returns, spy_data)

    def _plot_results(self, portfolio_returns: pd.Series, spy_data: pd.Series):
        # Creates a dark-mode tear sheet of the agent's performance and saves to PNG.
        print("[SYSTEM] Generating Performance Tear Sheet...")
        
        plt.style.use('dark_background')
        fig = plt.figure(figsize=(14, 10))
        gs = GridSpec(3, 1, height_ratios=[2, 1, 1])
        
        # Calculate Cumulative Returns
        portfolio_returns = portfolio_returns.dropna()
        cum_returns = portfolio_returns.cumsum()
        
        # Calculate SPY baseline (Buy & Hold) for comparison
        spy_returns = spy_data.pct_change().dropna().cumsum() * 100 
        
        # Subplot 1: Equity Curve
        ax1 = fig.add_subplot(gs[0])
        ax1.plot(cum_returns.index, cum_returns, color='#00ffcc', linewidth=2, label='Decoupled Agent (Stat-Arb)')
        ax1.plot(spy_returns.index, spy_returns, color='#555555', linewidth=1, linestyle='--', label='SPY Baseline')
        ax1.set_title('Historical Out-of-Sample Performance Estimate', fontsize=14, fontweight='bold')
        ax1.set_ylabel('Cumulative P&L (Dollar-Neutral)')
        ax1.grid(color='#222222', linestyle='--')
        ax1.legend(loc='upper left')
        
        # Calculate Drawdown
        rolling_max = cum_returns.cummax()
        drawdown = cum_returns - rolling_max
        
        # Subplot 2: Underwater Plot (Drawdown)
        ax2 = fig.add_subplot(gs[1], sharex=ax1)
        ax2.fill_between(drawdown.index, drawdown, 0, color='#ff3366', alpha=0.5)
        ax2.set_ylabel('Drawdown')
        ax2.set_title('Underwater Curve', fontsize=12)
        ax2.grid(color='#222222', linestyle='--')
        
        # Subplot 3: Daily Return Volatility
        ax3 = fig.add_subplot(gs[2], sharex=ax1)
        ax3.bar(portfolio_returns.index, portfolio_returns, color='#ffcc00', alpha=0.7)
        ax3.set_ylabel('Tick Returns')
        ax3.set_title('5-Minute Interval Returns Distribution', fontsize=12)
        ax3.grid(color='#222222', linestyle='--')
        
        plt.tight_layout()
        
        # Save the image instead of trying to open a GUI window inside Docker
        output_image = "backtest_tearsheet_3yr.png"
        plt.savefig(output_image, dpi=300, bbox_inches='tight', facecolor=fig.get_facecolor())
        print(f"\n[SUCCESS] Performance Tear Sheet saved as '{output_image}'")
        
        # Console Metrics
        print("\n====== ESTIMATED HISTORICAL PERFORMANCE ======")
        print(f"Total Cumulative P&L: ${cum_returns.iloc[-1]:.2f} (Per Unit Leveraged)")
        print(f"Max Drawdown:         ${drawdown.min():.2f}")
        print(f"Trade Density:        {len(portfolio_returns[portfolio_returns != 0])} Active 5-min intervals")
        print("==============================================")


if __name__ == "__main__":
    backtester = VectorizedBacktester()
    backtester.run_simulation()